const CodeMap = {
  500: ["None", "KC_NO", "other"],
  501: ["Reset", "RESET", "other"],
  569: ["", "KC_TRNS", "other"],
  65: ["A", "KC_A", "alpha"],
  66: ["B", "KC_B", "alpha"],
  67: ["C", "KC_C", "alpha"],
  68: ["D", "KC_D", "alpha"],
  69: ["E", "KC_E", "alpha"],
  70: ["F", "KC_F", "alpha"],
  71: ["G", "KC_G", "alpha"],
  72: ["H", "KC_H", "alpha"],
  73: ["I", "KC_I", "alpha"],
  74: ["J", "KC_J", "alpha"],
  75: ["K", "KC_K", "alpha"],
  76: ["L", "KC_L", "alpha"],
  77: ["M", "KC_M", "alpha"],
  78: ["N", "KC_N", "alpha"],
  79: ["O", "KC_O", "alpha"],
  80: ["P", "KC_P", "alpha"],
  81: ["Q", "KC_Q", "alpha"],
  82: ["R", "KC_R", "alpha"],
  83: ["S", "KC_S", "alpha"],
  84: ["T", "KC_T", "alpha"],
  85: ["U", "KC_U", "alpha"],
  86: ["V", "KC_V", "alpha"],
  87: ["W", "KC_W", "alpha"],
  88: ["X", "KC_X", "alpha"],
  89: ["Y", "KC_Y", "alpha"],
  90: ["Z", "KC_Z", "alpha"],
  49: ["1", "KC_1", "alpha"],
  50: ["2", "KC_2", "alpha"],
  51: ["3", "KC_3", "alpha"],
  52: ["4", "KC_4", "alpha"],
  53: ["5", "KC_5", "alpha"],
  54: ["6", "KC_6", "alpha"],
  55: ["7", "KC_7", "alpha"],
  56: ["8", "KC_8", "alpha"],
  57: ["9", "KC_9", "alpha"],
  48: ["0", "KC_0", "alpha"],
  13: ["Enter", "KC_ENTER", "spacing"],
  14: ["Enter", "KC_ENTER", "spacing"],
  27: ["Esc", "KC_ESCAPE", "spacing"],
  8: ["Backspace", "KC_BSPACE", "spacing"],
  9: ["Tab", "KC_TAB", "spacing"],
  32: ["Space", "KC_SPACE", "spacing"],
  189: ["-", "KC_MINUS", "punct"],
  187: ["=", "KC_EQUAL", "punct"],
  219: ["[", "KC_LBRACKET", "punct"],
  221: ["]", "KC_RBRACKET", "punct"],
  220: ["\\", "KC_BSLASH", "punct"],
  504: ["Non-US # and ~", "KC_NONUS_HASH", "punct"],
  186: [";", "KC_SCOLON", "punct"],
  222: ["'", "KC_QUOTE", "punct"],
  192: ["`", "KC_GRAVE", "punct"],
  188: [",", "KC_COMMA", "punct"],
  190: [".", "KC_DOT", "punct"],
  191: ["/", "KC_SLASH", "punct"],
  505: ["Caps", "KC_CAPSLOCK", "punct"],
  112: ["F1", "KC_F1", "func"],
  113: ["F2", "KC_F2", "func"],
  114: ["F3", "KC_F3", "func"],
  115: ["F4", "KC_F4", "func"],
  116: ["F5", "KC_F5", "func"],
  117: ["F6", "KC_F6", "func"],
  118: ["F7", "KC_F7", "func"],
  119: ["F8", "KC_F8", "func"],
  120: ["F9", "KC_F9", "func"],
  121: ["F10", "KC_F10", "func"],
  122: ["F11", "KC_F11", "func"],
  123: ["F12", "KC_F12", "func"],
  42: ["SysRq", "KC_PSCREEN", "nav"],
  137: ["Scroll lock", "KC_SLCK", "nav"],
  19: ["Pause", "KC_PAUSE", "other"],
  45: ["Ins", "KC_INSERT", "nav"],
  36: ["Home", "KC_HOME", "nav"],
  33: ["PgUp", "KC_PGUP", "nav"],
  46: ["Del", "KC_DELETE", "nav"],
  35: ["End", "KC_END", "nav"],
  34: ["PgDn", "KC_PGDOWN", "nav"],
  39: ["Right", "KC_RIGHT", "nav"],
  37: ["Left", "KC_LEFT", "nav"],
  40: ["Down", "KC_DOWN", "nav"],
  38: ["Up", "KC_UP", "nav"],
  136: ["Num", "KC_NUMLOCK", "num"],
  111: ["/", "KC_KP_SLASH", "num"],
  106: ["*", "KC_KP_ASTERISK", "num"],
  109: ["-", "KC_KP_MINUS", "num"],
  107: ["+", "KC_KP_PLUS", "num"],
  506: ["Enter", "KC_KP_ENTER", "num"],
  97: ["1", "KC_KP_1", "num"],
  98: ["2", "KC_KP_2", "num"],
  99: ["3", "KC_KP_3", "num"],
  100: ["4", "KC_KP_4", "num"],
  101: ["5", "KC_KP_5", "num"],
  102: ["6", "KC_KP_6", "num"],
  103: ["7", "KC_KP_7", "num"],
  104: ["8", "KC_KP_8", "num"],
  105: ["9", "KC_KP_9", "num"],
  96: ["0", "KC_KP_0", "num"],
  110: [".", "KC_KP_DOT", "num"],
  507: ["\\", "KC_NONUS_BSLASH", "other"],
  508: ["Application", "KC_APPLICATION", "nav"],
  509: ["Power", "KC_POWER", "other"],
  124: ["F13", "KC_F13", "func"],
  125: ["F14", "KC_F14", "func"],
  126: ["F15", "KC_F15", "func"],
  127: ["F16", "KC_F16", "func"],
  128: ["F17", "KC_F17", "func"],
  129: ["F18", "KC_F18", "func"],
  130: ["F19", "KC_F19", "func"],
  131: ["F20", "KC_F20", "func"],
  132: ["F21", "KC_F21", "func"],
  133: ["F22", "KC_F22", "func"],
  134: ["F23", "KC_F23", "func"],
  135: ["F24", "KC_F24", "func"],
  552: ["Undo", "KC_UNDO", "other"],
  553: ["Cut", "KC_CUT", "other"],
  554: ["Copy", "KC_COPY", "other"],
  555: ["Paste", "KC_PASTE", "other"],
  556: ["Find", "KC_FIND", "other"],
  557: ["\u1f507", "KC__MUTE", "other"],
  558: ["\u1f50a", "KC__VOLUP", "other"],
  559: ["\u1f509", "KC__VOLDOWN", "other"],
  560: [",", "KC_KP_COMMA", "other"],
  17: ["Ctrl", "KC_LCTL", "mods"],
  16: ["Shift", "KC_LSHIFT", "mods"],
  18: ["Alt", "KC_LALT", "mods"],
  91: ["Win", "KC_LGUI", "mods"],
  700: ["Right Ctrl", "KC_RCTRL", "mods"],
  701: ["Right Shift", "KC_RSHIFT", "mods"],
  702: ["AltGr", "KC_RALT", "mods"],
  92: ["Right Win", "KC_RGUI", "mods"],
  750: ["Power", "KC_SYSTEM_POWER", "system"],
  751: ["Sleep", "KC_SYSTEM_SLEEP", "system"],
  752: ["Wake", "KC_SYSTEM_WAKE", "system"],
  800: ["Mute", "KC_AUDIO_MUTE", "media"],
  801: ["VolUp", "KC_AUDIO_VOL_UP", "media"],
  802: ["VolDn", "KC_AUDIO_VOL_DOWN", "media"],
  803: ["Next", "KC_MEDIA_NEXT_TRACK", "media"],
  804: ["Prev", "KC_MEDIA_PREV_TRACK", "media"],
  805: ["Stop", "KC_MEDIA_STOP", "media"],
  806: ["Play", "KC_MEDIA_PLAY_PAUSE", "media"],
  808: ["Eject", "KC_MEDIA_EJECT", "media"],
  809: ["Mail", "KC_MAIL", "media"],
  810: ["Calc", "KC_CALCULATOR", "media"],
  811: ["File manager", "KC_MY_COMPUTER", "media"],
  812: ["Search", "KC_WWW_SEARCH", "media"],
  813: ["WWW Home", "KC_WWW_HOME", "media"],
  814: ["WWW Back", "KC_WWW_BACK", "media"],
  815: ["WWW Fwd", "KC_WWW_FORWARD", "media"],
  817: ["Refresh", "KC_WWW_REFRESH", "media"],
  818: ["Favorites", "KC_WWW_FAVORITES", "media"],
  819: ["Fast forward", "KC_MEDIA_FAST_FORWARD", "media"],
  820: ["Rewind", "KC_MEDIA_REWIND", "media"],
  901: ["Move up", "KC_MS_UP", "mouse"],
  902: ["Move down", "KC_MS_DOWN", "mouse"],
  903: ["Move left", "KC_MS_LEFT", "mouse"],
  904: ["Move right", "KC_MS_RIGHT", "mouse"],
  905: ["Left click", "KC_MS_BTN1", "mouse"],
  906: ["Right click", "KC_MS_BTN2", "mouse"],
  907: ["Middle click", "KC_MS_BTN3", "mouse"],
  908: ["Button 4", "KC_MS_BTN4", "mouse"],
  909: ["Button 5", "KC_MS_BTN5", "mouse"],
  910: ["Wheel Up", "KC_MS_WH_UP", "mouse"],
  911: ["Wheel Down", "KC_MS_WH_DOWN", "mouse"],
  912: ["Wheel Left", "KC_MS_WH_LEFT", "mouse"],
  913: ["Wheel Right", "KC_MS_WH_RIGHT", "mouse"],
  914: ["Acceleration 0", "KC_MS_ACCEL0", "mouse"],
  915: ["Acceleration 1", "KC_MS_ACCEL1", "mouse"],
  916: ["Acceleration 2", "KC_MS_ACCEL2", "mouse"],
  1199: ["Shift", "SFT_T()", "dual_function"],
  1200: ["Hyper", "ALL_T()", "dual_function"],
  1201: ["Alt", "ALT_T()", "dual_function"],
  1202: ["Ctrl", "CTL_T()", "dual_function"],
  1203: ["Cmd/Win", "GUI_T()", "dual_function"],
  1214: ["Meh", "MEH_T()", "dual_function"],
  1204: ["Alt +", "LALT()", "shortcuts"],
  1205: ["AltGr +", "RALT()", "shortcuts"],
  1206: ["Ctrl +", "LCTL()", "shortcuts"],
  1207: ["Shift +", "LSFT()", "shortcuts"],
  1208: ["Cmd/Win +", "LGUI()", "shortcuts"],
  1209: ["Hyper +", "HYPR()", "shortcuts"],
  1210: ["Meh +", "MEH()", "shortcuts"],
  1211: ["LCAG", "LCAG()", "shortcuts"],
  1212: ["Shift (", "KC_LSPO", "other"],
  1213: ["Shift )", "KC_RSPC", "other"],
  1400: ["LT", "LT()", "layer_shortcuts"],
  1e3: ["TG", "TG()", "layer"],
  1001: ["MO", "MO()", "layer"],
  1002: ["OSL", "OSL()", "layer"],
  1003: ["TO", "TO()", "layer"],
  1500: ["!", "KC_EXLM", "shifted_punct"],
  1501: ["@", "KC_AT", "shifted_punct"],
  1502: ["{", "KC_LCBR", "shifted_punct"],
  1503: ["}", "KC_RCBR", "shifted_punct"],
  1504: ["|", "KC_PIPE", "shifted_punct"],
  1505: ["#", "KC_HASH", "shifted_punct"],
  1506: ["$", "KC_DLR", "shifted_punct"],
  1507: ["(", "KC_LPRN", "shifted_punct"],
  1508: [")", "KC_RPRN", "shifted_punct"],
  1509: ["%", "KC_PERC", "shifted_punct"],
  1510: ["^", "KC_CIRC", "shifted_punct"],
  1511: ["&", "KC_AMPR", "shifted_punct"],
  1512: ["*", "KC_ASTR", "shifted_punct"],
  1513: ["+", "KC_PLUS", "shifted_punct"],
  1514: ["~", "KC_TILD", "shifted_punct"],
  1515: ["VERSION", "VRSN", "other"],
  1516: [":", "KC_COLN", "shifted_punct"],
  1517: ["_", "KC_UNDS", "shifted_punct"],
  1518: ["%", "KC_PERC", "shifted_punct"],
  1600: ["\xbd", "NO_HALF", "nordic"],
  1601: ["+", "NO_PLUS", "nordic"],
  1602: ["'", "NO_ACUT", "nordic"],
  1603: ["\xe5", "NO_AM", "nordic"],
  1604: ['"', "NO_QUOT", "nordic"],
  1605: ["\xf8", "NO_AE", "nordic"],
  1606: ["\xe6", "NO_OSLH", "nordic"],
  1607: ["'", "NO_APOS", "nordic"],
  1608: ["<", "NO_LESS", "nordic"],
  1609: ["-", "NO_MINS", "nordic"],
  1611: ["NO_QUO2", "NO_QUO2", "nordic"],
  1612: ["NO_BULT", "NO_BULT", "nordic"],
  1613: ["&", "NO_AMPR", "nordic"],
  1614: ["/", "NO_SLSH", "nordic"],
  1615: ["(", "NO_LPRN", "nordic"],
  1616: [")", "NO_RPRN", "nordic"],
  1617: ["=", "NO_EQL", "nordic"],
  1618: ["?", "NO_QUES", "nordic"],
  1619: ["`", "NO_GRV", "nordic"],
  1620: ["^", "NO_CIRC", "nordic"],
  1621: [">", "NO_GRTR", "nordic"],
  1622: [";", "NO_SCLN", "nordic"],
  1623: [":", "NO_COLN", "nordic"],
  1624: ["_", "NO_UNDS", "nordic"],
  1625: ["@", "NO_AT", "nordic"],
  1626: ["#", "NO_PND", "nordic"],
  1628: ["\xb6", "NO_LCBR", "nordic"],
  1629: ["[", "NO_LBRC", "nordic"],
  1630: ["]", "NO_RBRC", "nordic"],
  1631: ["\u2260", "NO_RCBR", "nordic"],
  1632: ["<", "NO_PIPE", "nordic"],
  1633: ["\u20ac", "NO_EURO", "nordic"],
  1634: ["~", "NO_TILD", "nordic"],
  1636: ["NO_MU", "NO_MU", "nordic"],
  1637: ["German Z", "DE_Z", "nordic"],
  1638: ["German Y", "DE_Y", "nordic"],
  1639: ["German \xdf", "DE_SS", "nordic"],
  1640: ["German \xc6", "DE_AE", "nordic"],
  1641: ["German \xdc", "DE_UE", "nordic"],
  1642: ["German \xd6", "DE_OE", "nordic"],
  1643: ["German accent circumflex ^ and ring \xb0", "DE_CIRC", "nordic"],
  1644: ["German accent acute \xb4 and grave `", "DE_ACUT", "nordic"],
  1645: ["German + and * and ~", "DE_PLUS", "nordic"],
  1646: ["German # and '", "DE_HASH", "nordic"],
  1647: ["German < and > and |", "DE_LESS", "nordic"],
  1648: ["German - and _", "DE_MINS", "nordic"],
  1649: ["German \xb0", "DE_RING", "nordic"],
  1650: ["German !", "DE_EXLM", "nordic"],
  1651: ['German "', "DE_DQOT", "nordic"],
  1652: ["German \xa7", "DE_PARA", "nordic"],
  1653: ["German $", "DE_DLR", "nordic"],
  1654: ["German %", "DE_PERC", "nordic"],
  1655: ["German &", "DE_AMPR", "nordic"],
  1656: ["German /", "DE_SLSH", "nordic"],
  1657: ["German (", "DE_LPRN", "nordic"],
  1658: ["German )", "DE_RPRN", "nordic"],
  1659: ["German =", "DE_EQL", "nordic"],
  1660: ["German ?", "DE_QST", "nordic"],
  1661: ["German `", "DE_GRV", "nordic"],
  1662: ["German *", "DE_ASTR", "nordic"],
  1663: ["German '", "DE_QUOT", "nordic"],
  1664: ["German >", "DE_MORE", "nordic"],
  1665: ["German :", "DE_COLN", "nordic"],
  1666: ["German ;", "DE_SCLN", "nordic"],
  1667: ["German _", "DE_UNDS", "nordic"],
  1668: ["German \xb2", "DE_SQ2", "nordic"],
  1669: ["German \xb3", "DE_SQ3", "nordic"],
  1670: ["German {", "DE_LCBR", "nordic"],
  1671: ["German [", "DE_LBRC", "nordic"],
  1672: ["German ]", "DE_RBRC", "nordic"],
  1673: ["German }", "DE_RCBR", "nordic"],
  1674: ["German backslash", "DE_BSLS", "nordic"],
  1675: ["German @", "DE_AT", "nordic"],
  1676: ["German \u20ac", "DE_EURO", "nordic"],
  1677: ["German ~", "DE_TILD", "nordic"],
  1678: ["German |", "DE_PIPE", "nordic"]
};
